#!/usr/bin/env bash

wallpaper_dir="${HOME}/.wallpapers"
current_wallpaper=$(basename "$(swww query)" | head -n 1)

function _waybar_change_wallpaper() {
    local wallpaper="$(ls "${wallpaper_dir}" | shuf --random-source=/dev/urandom -n 1)"

    if [ ! "${current_wallpaper}" = "${wallpaper}" ]; then
        swww img --transition-fps 60 --transition-type wipe --transition-duration 3 "${wallpaper_dir}/${wallpaper}"
    else
        local total_wallpapers=$(find "${wallpaper_dir}" -maxdepth 1 -type f | wc -l)

        if [ "${total_wallpapers}" -gt 1 ]; then
            _waybar_change_wallpaper
        fi
    fi
}

_waybar_change_wallpaper
